kibot:
  version: 1

preflight:
  erc: true
  drc: true
  check_zone_fills: true

outputs:
  - name: 'Schematic PDF'
    type: pdf_sch_print

  - name: 'Interactive BOM'
    type: ibom

  - name: '3D model - .step'
    type : step

  - name: 'renders'
    type: blender_export
    options:
      render_options:
        transparent_background: true
        samples: 10
      fixed_auto_camera: true
      auto_camera_z_axis_factor: 1.5
      default_file_id: '_%03d'
      outputs:
        - type: render