name: "KiCad DRC / ERC Check"
on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  drcerc:
    name: Determine version, Test, Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Enable caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name : Install KiCad
        uses: actions-for-kicad/setup-kicad@v1.0
        with:
          version: '8.4'

      - name: Generate PDF
        uses: actions-for-kicad/generate-kicad-files@v1.0
        with:
          file: './file.kicad_sch'
          type: 'schematic_pdf'

      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: 'file.pdf'
          path: './file.pdf'