kicost:
  version: 1
  cache_ttl: 7
  cache_path: ~/.cache/kicost


APIs:
  Mouser:
    # Mouser Part API key
    key: dc0adc55-67a3-418b-ac46-981bb25c51e8
    enable: true
    cache_path: ~/.cache/kicost/Mouser
